services:
  postgres:
    image: postgres:17
    container_name: jokahobby-postgres
    ports:
      - "5499:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - jokahobby-pgdata:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  jokahobby-pgdata:
