-- Hobby Role System: Host + Manager hierarchy

-- 1. Create hobby_host table (1 host per hobby)
CREATE TABLE hobby_host (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    hobby_id BIGINT NOT NULL UNIQUE,
    account_id UUID NOT NULL,
    transferred_by UUID,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_hobby_host_hobby FOREIGN KEY (hobby_id) REFERENCES hobby(id),
    CONSTRAINT fk_hobby_host_account FOREIGN KEY (account_id) REFERENCES account(id),
    CONSTRAINT fk_hobby_host_transferred_by FOREIGN KEY (transferred_by) REFERENCES account(id)
);

-- 2. Add promoted_by column to hobby_manager
ALTER TABLE hobby_manager ADD COLUMN promoted_by UUID;

-- 3. Set promoted_by for existing managers (self-promoted for initial creators)
UPDATE hobby_manager SET promoted_by = account_id;

-- 4. Make promoted_by NOT NULL
ALTER TABLE hobby_manager ALTER COLUMN promoted_by SET NOT NULL;

-- 5. Add FK constraint for promoted_by
ALTER TABLE hobby_manager ADD CONSTRAINT fk_hobby_manager_promoted_by
    FOREIGN KEY (promoted_by) REFERENCES account(id);

-- 6. Migrate: oldest manager per hobby becomes host
INSERT INTO hobby_host (hobby_id, account_id, created_at, updated_at)
SELECT hm.hobby_id, hm.account_id, hm.created_at, hm.updated_at
FROM hobby_manager hm
WHERE hm.id = (
    SELECT MIN(hm2.id) FROM hobby_manager hm2
    WHERE hm2.hobby_id = hm.hobby_id
);

-- 7. Remove migrated managers (now hosts) from hobby_manager
DELETE FROM hobby_manager WHERE id IN (
    SELECT MIN(id) FROM hobby_manager GROUP BY hobby_id
);
